import HighPrecision_ADDA as converter
import time
import math
import threading

conv = converter.AD_DA()

while True:
    a = conv.ReadChannel(0, conv.data_format.voltage)
    b = conv.ReadChannel(1, conv.data_format.voltage)
    c = conv.ReadChannel(2, conv.data_format.voltage)
    d = conv.ReadChannel(3, conv.data_format.voltage)
    e = conv.ReadChannel(4, conv.data_format.voltage)
    f = conv.ReadChannel(5, conv.data_format.voltage)
    g = conv.ReadChannel(6, conv.data_format.voltage)
    h = conv.ReadChannel(7, conv.data_format.voltage)
    i = conv.ReadChannel(8, conv.data_format.voltage)
    j = conv.ReadChannel(9, conv.data_format.voltage)
    k = conv.ReadChannel(10, conv.data_format.voltage)
    l = conv.ReadChannel(11, conv.data_format.voltage)
    m = conv.ReadChannel(12, conv.data_format.voltage)
    n = conv.ReadChannel(13, conv.data_format.voltage)
    o = conv.ReadChannel(14, conv.data_format.voltage)
    p = conv.ReadChannel(15, conv.data_format.voltage)

    a = float(a)
    b = float(b)
    c = float(c)
    d = float(d)
    e = float(e)
    f = float(f)
    g = float(g)
    h = float(h)
    i = float(i)
    j = float(j)
    k = float(k)
    l = float(l)
    m = float(m)
    n = float(n)
    o = float(o)
    p = float(p)

    a = round(a, 2)
    b = round(b, 2)
    c = round(c, 2)
    d = round(d, 2)
    e = round(e, 2)
    f = round(f, 2)
    g = round(g, 2)
    h = round(h, 2)
    i = round(i, 2)
    j = round(j, 2)
    k = round(k, 2)
    l = round(l, 2)
    m = round(m, 2)
    n = round(n, 2)
    o = round(o, 2)
    p = round(p, 2)

    print("a=",a, "b=",b,"c=",c,"d=",d, "e=",e, "f=",f, "g=",g,"h=",h,"i=",i, "j=",j, "k=",k, "l=",l,"m=",m,"n=",n, "o=",o, "p=",p)
    # print("a=", a, "b=", b)

    time.sleep(0.1)